services:
  api:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  worker:
    build:
      context: .
      dockerfile: docker/worker.Dockerfile
    env_file: .env
    depends_on:
      - redis

  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: adlaw
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
